# Generated by Django 5.2 on 2025-05-24 17:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("django_a2a", "0001_initial"),
        ("django_a2a", "0002_alter_task_session_id"),
        ("django_a2a", "0003_remove_artifact_append_remove_artifact_id_and_more"),
        ("django_a2a", "0004_rename_type_part_kind_remove_message_id_and_more"),
        ("django_a2a", "0005_alter_artifact_artifactid_alter_message_messageid"),
        ("django_a2a", "0006_alter_artifact_artifactid"),
        ("django_a2a", "0007_remove_part_artifact_remove_part_message"),
        ("django_a2a", "0008_part_artifact_part_message"),
        ("django_a2a", "0009_artifact_created_on_artifact_updated_on_and_more"),
        ("django_a2a", "0010_remove_taskstatus_message"),
        ("django_a2a", "0011_taskstatus_message"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "contextId",
                    models.CharField(
                        blank=True, default=uuid.uuid4, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("agent", "Agent")], max_length=10
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="django_a2a.task",
                    ),
                ),
                ("contextId", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "kind",
                    models.CharField(default="message", editable=False, max_length=10),
                ),
                (
                    "messageId",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("bytes", models.TextField(blank=True, null=True)),
                ("uri", models.URLField(blank=True, null=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="django_a2a.task",
                    ),
                ),
                (
                    "artifactId",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "Text"), ("file", "File"), ("data", "Data")],
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_a2a.filecontent",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="django_a2a.artifact",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="django_a2a.message",
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("working", "Working"),
                            ("input-required", "Input Required"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                            ("auth-required", "Auth Required"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="django_a2a.task",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_message",
                        to="django_a2a.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
