# Generated by Django 5.2 on 2025-05-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="session_id",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
