# Generated by Django 5.2 on 2025-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0002_alter_task_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="append",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="id",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="index",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="last_chunk",
        ),
        migrations.AddField(
            model_name="artifact",
            name="artifactId",
            field=models.CharField(
                default="3c86a597-4321-47d5-a0bc-8dccf53465f5",
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
