# Generated by Django 5.2 on 2025-05-24 15:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0003_remove_artifact_append_remove_artifact_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="type",
            new_name="kind",
        ),
        migrations.RemoveField(
            model_name="message",
            name="id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="session_id",
        ),
        migrations.AddField(
            model_name="message",
            name="contextId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="kind",
            field=models.CharField(default="message", editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name="message",
            name="messageId",
            field=models.CharField(
                default="28c72aaf-c695-451b-b158-ff6995e9b8e1",
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="contextId",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="artifactId",
            field=models.CharField(
                default="ca542e6a-c77d-44fb-ba0f-faf6b18c3640",
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="state",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("working", "Working"),
                    ("input-required", "Input Required"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected"),
                    ("auth-required", "Auth Required"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
