# Generated by Django 5.2 on 2025-05-24 15:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0004_rename_type_part_kind_remove_message_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="artifactId",
            field=models.CharField(
                default="c632a83f-8a98-4da5-988d-5a7d909eb081",
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="messageId",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
