# Generated by Django 5.2 on 2025-05-24 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0005_alter_artifact_artifactid_alter_message_messageid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="artifactId",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
