# Generated by Django 5.2 on 2025-05-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0006_alter_artifact_artifactid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="artifact",
        ),
        migrations.RemoveField(
            model_name="part",
            name="message",
        ),
    ]
