# Generated by Django 5.2 on 2025-05-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0007_remove_part_artifact_remove_part_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="artifact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="django_a2a.artifact",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="django_a2a.message",
            ),
        ),
    ]
