# Generated by Django 5.2 on 2025-05-24 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0008_part_artifact_part_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="artifact",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="filecontent",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="message",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="message",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="part",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
