# Generated by Django 5.2 on 2025-05-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0009_artifact_created_on_artifact_updated_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskstatus",
            name="message",
        ),
    ]
