# Generated by Django 5.2 on 2025-05-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0010_remove_taskstatus_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatus",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_message",
                to="django_a2a.message",
            ),
        ),
    ]
