# Generated by Django 5.2 on 2025-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_a2a", "0001_squashed_0011_taskstatus_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="state",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("working", "Working"),
                    ("input-required", "Input Required"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected"),
                    ("auth-required", "Auth Required"),
                    ("unknown", "Unknown"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
